ros2_kdl_action_client:
  ros__parameters:
    cmd_interface: "position"
    traj_type: "linear"
    s_type: "trapezoidal"

    traj_duration: 10.0
    acc_duration: 0.5
    total_time: 10.0
    trajectory_len: 200.0
    Kp: 5.0
    end_position: [-0.6, 0.3, 0.1]

    #ctrl: "velocity_ctrl"