ros2_kdl_node:
  ros__parameters:
    cmd_interface: "position"
    traj_type: "linear"
    s_type: "trapezoidal"

    traj_duration: 5.0
    acc_duration: 1.0
    total_time: 5.0
    trajectory_len: 50.0
    Kp: 10.0
    end_position: [0.2, 0.0, 0.2]
