/ros2_kdl_node:
  ros__parameters:
    cmd_interface: "position"
    traj_duration: 5.0
    acc_duration: 1.0
    total_time: 10.0
    trajectory_len: 500.0
    Kp: 1.5
    end_position: [0.25, 0.0, 0.35]

    #ctrl: "velocity_ctrl"
